const JSZip=require('jszip');
const {DOMParser}=require('@xmldom/xmldom');
const children=n=>Array.from(n.childNodes||[]).filter(x=>x.nodeType===1);
const tag=n=>n.localName||n.nodeName?.split(':').at(-1);
const direct=(n,t)=>children(n).filter(x=>tag(x)===t);
const descendants=(n,t)=>Array.from(n.getElementsByTagName('*')).filter(x=>tag(x)===t);
const attr=(n,k)=>n?.getAttribute('w:'+k)||n?.getAttribute(k)||'';
function xml(s){if(/<!DOCTYPE|<!ENTITY/i.test(s))throw new Error('XML с внешними сущностями не поддерживается');return new DOMParser({errorHandler:{warning:()=>{},error:()=>{throw new Error('Поврежден XML документа')},fatalError:()=>{throw new Error('Поврежден XML документа')}}}).parseFromString(s,'text/xml');}
function text(n){if(tag(n)==='del')return '';if(tag(n)==='t')return n.textContent;if(['tab','br','cr'].includes(tag(n)))return tag(n)==='tab'?'\t':'\n';return children(n).map(text).join('');}
async function parse(buffer){
 const zip=await JSZip.loadAsync(buffer);if(Object.values(zip.files).reduce((s,f)=>s+(f._data?.uncompressedSize||0),0)>50*1024*1024)throw new Error('Распакованный документ больше 50 МБ');
 if(!zip.file('word/document.xml'))throw new Error('Файл не является документом DOCX');
 const document=xml(await zip.file('word/document.xml').async('string')),body=descendants(document,'body')[0];
 if(!body)throw new Error('Не найдена основная часть документа');
 if(descendants(body,'altChunk').length||descendants(body,'txbxContent').length||descendants(body,'drawing').length||descendants(body,'pict').length||descendants(body,'object').length||descendants(body,'footnoteReference').length||descendants(body,'endnoteReference').length)throw new Error('Документ содержит изображения, объекты или сноски. Для этого режима подготовьте текстовую копию DOCX без них, чтобы не потерять содержимое.');
 const numbering=zip.file('word/numbering.xml')?xml(await zip.file('word/numbering.xml').async('string')):null,nums=new Map(),abstracts=new Map(),counts=new Map();
 if(numbering){for(const a of descendants(numbering,'abstractNum'))abstracts.set(attr(a,'abstractNumId'),new Map(direct(a,'lvl').map(l=>[+attr(l,'ilvl'),{start:+attr(direct(l,'start')[0],'val')||1,format:attr(direct(l,'numFmt')[0],'val'),pattern:attr(direct(l,'lvlText')[0],'val')}])));for(const n of descendants(numbering,'num'))nums.set(attr(n,'numId'),{abstract:attr(direct(n,'abstractNumId')[0],'val'),overrides:new Map(direct(n,'lvlOverride').map(l=>[+attr(l,'ilvl'),+attr(direct(l,'startOverride')[0],'val')||1]))});}
 const blocks=[],warnings=[];let serial=0;
 function number(p){const pr=direct(p,'pPr')[0],np=pr&&direct(pr,'numPr')[0];if(!np)return '';const id=attr(direct(np,'numId')[0],'val');if(id==='0')return '';const level=+attr(direct(np,'ilvl')[0],'val')||0,n=nums.get(id),levels=abstracts.get(n?.abstract),spec=levels?.get(level);if(!spec)throw new Error('Не удалось восстановить автоматическую нумерацию');const state=counts.get(id)||[];state[level]=(state[level]??((n.overrides.get(level)??spec.start)-1))+1;state.length=level+1;counts.set(id,state);if(spec.format==='bullet')return '• ';if(!['decimal','decimalZero'].includes(spec.format))throw new Error('Нестандартная нумерация: сохраните номера пунктов обычным текстом');return spec.pattern.replace(/%(\d+)/g,(_,v)=>String(state[+v-1]??levels.get(+v-1)?.start??1))+' ';}
 function read(n){if(tag(n)==='del')return null;if(tag(n)==='p'){const raw=text(n).trim(),prefix=number(n);if(!raw)return null;if(raw.length>12000)throw new Error('Один абзац содержит более 12 000 знаков. Разделите его на несколько абзацев.');const pr=direct(n,'pPr')[0],style=attr(pr&&direct(pr,'pStyle')[0],'val'),heading=/heading|title/i.test(style)||(/^[\d.]*\s*[А-ЯЁA-Z][А-ЯЁA-Z\s.,\-–—№\d]+$/.test(raw)&&raw.length<150);const b={id:'p'+(++serial),source:prefix+raw,prefix,heading,translation:''};blocks.push(b);return {type:'paragraph',id:b.id};}
 if(tag(n)==='tbl'){return {type:'table',grid:direct(n,'tblGrid').flatMap(g=>direct(g,'gridCol').map(c=>+attr(c,'w')||1)),rows:direct(n,'tr').map(tr=>({cells:direct(tr,'tc').map(tc=>{const pr=direct(tc,'tcPr')[0];if(pr&&direct(pr,'vMerge').length)warnings.push('Вертикально объединенные ячейки представлены отдельными строками; текст сохранен в первой ячейке.');return {span:+attr(pr&&direct(pr,'gridSpan')[0],'val')||1,blocks:children(tc).map(read).filter(Boolean)};})}))};}if(['sdt','sdtContent','ins'].includes(tag(n)))return {type:'group',blocks:children(n).map(read).filter(Boolean)};return null;}
 const tree=children(body).map(read).filter(Boolean);if(!blocks.length)throw new Error('В документе нет доступного текста');if(blocks.length>1200||blocks.reduce((n,b)=>n+b.source.length,0)>300000)throw new Error('Документ слишком большой: разделите его на части до 300 000 знаков');
 if(descendants(body,'ins').length||descendants(body,'del').length)warnings.push('Использована итоговая версия текста: вставки учтены, удаленные фрагменты исключены.');
 for(const name of Object.keys(zip.files).filter(n=>/^word\/(header|footer)\d+\.xml$/.test(n))){const part=xml(await zip.file(name).async('string'));const visible=text(part).trim();if(visible.replace(/[\d\s.\/–—-]|стр(?:аница)?\.?|page|of/gi,'').length>0)warnings.push('В колонтитулах есть текст, не включенный в перевод. Проверьте его в исходнике.');}
 const all=blocks.map(b=>b.source).join(' '),ru=(all.match(/[А-Яа-яЁё]/g)||[]).length,en=(all.match(/[a-z]/gi)||[]).length;
 return {blocks,tree,sourceLanguage:ru>en?'ru':'en',warnings:[...new Set(warnings)]};
}
function validateTranslation(source,translation){if(typeof translation!=='string'||!translation.trim()||translation.length>Math.max(20000,source.length*5))throw new Error('Пустой или некорректный перевод');const digits=s=>(s.match(/\d+(?:[.,]\d+)*/g)||[]).map(x=>x.replace(/,/g,'.')).sort();const tokens=s=>(s.match(/[\w.+-]+@[\w.-]+\.[a-z]{2,}|https?:\/\/[^\s<>]+|_{3,}/gi)||[]).sort();const issues=[];if(JSON.stringify(digits(source))!==JSON.stringify(digits(translation)))issues.push('Проверьте числа, даты и номера пунктов');if(JSON.stringify(tokens(source))!==JSON.stringify(tokens(translation)))issues.push('Проверьте адреса, ссылки и незаполненные поля');return issues;}
module.exports={parse,validateTranslation};
