const {Document,Packer,Paragraph,TextRun,Table,TableRow,TableCell,WidthType,TableLayoutType,VerticalAlign,AlignmentType,Footer,PageNumber,PageOrientation}=require('docx');
const borders=Object.fromEntries(['top','bottom','left','right','insideHorizontal','insideVertical'].map(k=>[k,{style:'single',size:4,color:'B7B7B7'}]));
async function exportDocument(d){if(d.pdf?.pages.some(p=>p.status!=='done'))throw new Error('Сначала дождитесь чтения всех страниц PDF');if(!d.blocks.length||d.blocks.some(b=>!b.translation))throw new Error('Перевод еще не завершен');const map=new Map(d.blocks.map(b=>[b.id,b]));
const paragraph=(b,lang,compact=false)=>new Paragraph({alignment:b.heading?AlignmentType.CENTER:AlignmentType.JUSTIFIED,spacing:{after:80,line:240},children:String(lang===d.sourceLanguage?b.source:b.translation).replace(/[ \t]{2,}/g,' ').split('\n').map((s,i)=>new TextRun({text:s,break:i?1:undefined,font:'Times New Roman',size:compact?17:20,bold:b.heading,color:'000000'}))});
const render=(nodes,lang,compact=false)=>nodes.flatMap(n=>n.type==='paragraph'?[paragraph(map.get(n.id),lang,compact)]:n.type==='group'?render(n.blocks,lang,compact):[table(n,lang)]);
function cell(nodes,lang,span=1,compact=false){const rows=render(nodes,lang,compact);return new TableCell({columnSpan:span,verticalAlign:VerticalAlign.TOP,margins:{top:65,bottom:65,left:100,right:100},children:rows.length?[...rows,...(rows[rows.length-1] instanceof Table?[new Paragraph({spacing:{after:0,before:0},children:[]})]:[])]:[new Paragraph('')]});}
function table(n,lang){const count=Math.max(...n.rows.map(r=>r.cells.reduce((s,c)=>s+c.span,0)));const weights=n.grid?.length===count?n.grid:Array(count).fill(1),sum=weights.reduce((a,b)=>a+b,0);return new Table({width:{size:7482,type:WidthType.DXA},columnWidths:weights.map(w=>Math.floor(7482*w/sum)),layout:TableLayoutType.FIXED,borders,rows:n.rows.map(r=>new TableRow({children:r.cells.map(c=>cell(c.blocks,lang,c.span,true))}))});}
const rows=[];for(const n of d.tree){if(n.type==='table'){for(const row of n.rows)rows.push(new TableRow({children:['ru','en'].map(lang=>new TableCell({width:{size:50,type:WidthType.PERCENTAGE},children:[table({rows:[row],grid:n.grid},lang),new Paragraph({spacing:{after:0,before:0},children:[]})],margins:{top:50,bottom:50,left:100,right:100}}))}));}else rows.push(new TableRow({children:['ru','en'].map(lang=>cell([n],lang))}));}
const doc=new Document({creator:'AI Corp Chat',title:d.title,styles:{default:{document:{run:{font:'Times New Roman',size:20}}}},sections:[{properties:{page:{size:{orientation:PageOrientation.LANDSCAPE,width:11906,height:16838},margin:{top:680,bottom:567,left:737,right:737}}},footers:{default:new Footer({children:[new Paragraph({alignment:AlignmentType.CENTER,children:[new TextRun({children:[PageNumber.CURRENT],font:'Times New Roman',size:18})]})]})},children:[new Table({width:{size:15364,type:WidthType.DXA},columnWidths:[7682,7682],layout:TableLayoutType.FIXED,borders,rows})]}]});return Packer.toBuffer(doc);}
module.exports={exportDocument};
