import React, {useEffect,useRef,useState} from 'react';
import {Link} from 'react-router-dom';
import {ArrowLeft,ArrowUp,Plus,Paperclip,Download,Maximize2,Minimize2,Trash2,X,LoaderCircle} from 'lucide-react';
import {useAuthContext} from '~/hooks/AuthContext';
import {BilingualChatContainer} from './BilingualViewportChat';
import './Bilingual.css';
const ObsoleteSession = class extends Error {};
type ManualEdit={source:string;translation:string;revision:number};
type Block={id:string;source:string;translation:string;heading:boolean;issues?:string[]};
type Tree={type:string;id?:string;blocks?:Tree[];rows?:{cells:{span:number;blocks:Tree[]}[]}[]};
type Doc={pdf?:{pageCount:number;pages:{number:number;status:string}[]};tree?:Tree[];id:string;title:string;filename?:string;revision:number;status:string;sourceLanguage:string;blocks:Block[];chat:{role:string;text:string}[];warnings:string[];progress?:string;error?:string};
export default function Bilingual(){
 const {token,user}=useAuthContext();const owner=user?.id||'';const [renderedOwner,setRenderedOwner]=useState(owner);const account=useRef({owner,epoch:0});if(account.current.owner!==owner)account.current={owner,epoch:account.current.epoch+1};const [items,setItems]=useState<Doc[]>([]),[doc,setDoc]=useState<Doc|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[preview,setPreview]=useState(false),[collapsed,setCollapsed]=useState(false),[selected,setSelected]=useState(''),[edit,setEdit]=useState<ManualEdit|null>(null);
 const fileRef=useRef<HTMLInputElement>(null),scroll=useRef<HTMLDivElement>(null),active=useRef(''),operation=useRef(false),pending=useRef<{id:string;message:string;selectedId:string;docId:string}|null>(null);
 const sessionEpoch=account.current.epoch;
 const api=async(p:string,method='GET',body?:unknown)=>{const epoch=sessionEpoch;const check=()=>{if(account.current.epoch!==epoch)throw new ObsoleteSession();};check();const r=await fetch(`/api/bilingual${p}`,{method,headers:{Authorization:`Bearer ${token}`,...(body&&!(body instanceof FormData)?{'Content-Type':'application/json'}:{})},body:body instanceof FormData?body:body?JSON.stringify(body):undefined});check();if(!r.ok){let text=`Ошибка ${r.status}`;try{const j=await r.json();text=j.error||j.message||text;}catch{}check();throw new Error(text);}return {json:async()=>{const data=await r.json();check();return data;},blob:async()=>{const data=await r.blob();check();return data;}};};
 const accept=(d:Doc|null)=>{active.current=d?.id||'';setDoc(d);};
 const list=async()=>setItems(await(await api('')).json());
 const run=async(fn:()=>Promise<void>)=>{if(operation.current||!owner)return;const epoch=account.current.epoch;operation.current=true;setBusy(true);setError('');try{await fn();}catch(e){if(account.current.epoch===epoch&&!(e instanceof ObsoleteSession))setError((e as Error).message);}finally{if(account.current.epoch===epoch){operation.current=false;setBusy(false);}}};
 useEffect(()=>{setRenderedOwner(owner);setItems([]);accept(null);setPreview(false);setSelected('');setEdit(null);setMessage('');setError('');setBusy(false);operation.current=false;pending.current=null;},[owner]);
 useEffect(()=>{if(owner&&token)void list().catch(e=>{if(account.current.epoch===sessionEpoch&&!(e instanceof ObsoleteSession))setError((e as Error).message);});},[owner,token]);
 useEffect(()=>{scroll.current?.scrollTo({top:scroll.current.scrollHeight,behavior:'smooth'});},[doc?.chat.length]);
 useEffect(()=>{if(doc?.status!=='processing')return;let stopped=false;let timer:ReturnType<typeof setTimeout>;const id=doc.id;const poll=async()=>{try{const next=await(await api(`/${id}`)).json();if(!stopped&&active.current===id){setDoc(next);if(next.status!=='processing')await list();}}catch(e){if(!stopped&&!(e instanceof ObsoleteSession))setError((e as Error).message);}if(!stopped)timer=setTimeout(poll,1500);};timer=setTimeout(poll,1000);return()=>{stopped=true;clearTimeout(timer);};},[doc?.id,doc?.status,token,owner]);
 const locked=busy||doc?.status==='processing',complete=!!doc?.blocks.length&&doc.blocks.every(b=>b.translation)&&!doc.pdf?.pages.some(p=>p.status!=='done'),chosen=doc?.blocks.find(b=>b.id===selected);
 const ensure=async()=>{if(doc)return doc;const d=await(await api('','POST',{})).json();accept(d);return d;};
 const submit=()=>run(async()=>{if(locked||!message.trim())return;const d=await ensure();if(!pending.current||pending.current.message!==message||pending.current.selectedId!==selected||pending.current.docId!==d.id)pending.current={id:crypto.randomUUID(),message,selectedId:selected,docId:d.id};accept(await(await api(`/${d.id}/chat`,'POST',{message,selectedId:selected,requestId:pending.current.id})).json());pending.current=null;setMessage('');await list();});
 const upload=(file?:File)=>run(async()=>{if(!file)return;if(!/\.(docx|pdf)$/i.test(file.name))throw new Error('Выберите документ DOCX или PDF');if(file.size>20*1024*1024)throw new Error('Размер файла не должен превышать 20 МБ');const d=await ensure();const data=new FormData();data.append('file',file);accept(await(await api(`/${d.id}/file`,'POST',data)).json());await list();accept(await(await api(`/${d.id}/chat`,'POST',{message:'Подготовь полный билингвальный перевод документа. Сохрани нумерацию, таблицы, реквизиты и все условия исходника.',requestId:crypto.randomUUID()})).json());await list();});
 const download=()=>run(async()=>{if(!doc)return;const r=await api(`/${doc.id}/export`),url=URL.createObjectURL(await r.blob()),a=document.createElement('a');a.href=url;a.download=`${doc.title}_RU_EN_v${doc.revision}.docx`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
 const pick=(b:Block)=>{setSelected(b.id);setEdit(null);setCollapsed(false);};
 const remove=(item:Doc)=>run(async()=>{if(!window.confirm(`Удалить перевод «${item.title}» из списка?`))return;await api(`/${item.id}`,'DELETE');if(active.current===item.id){accept(null);setPreview(false);setSelected('');}await list();});
 const saveManual=()=>run(async()=>{if(!doc||!chosen||!edit)return;accept(await(await api(`/${doc.id}/block/${chosen.id}`,'PATCH',edit)).json());setEdit(null);await list();});
 const tree:Tree[]=doc?.tree||doc?.blocks.map(b=>({type:'paragraph',id:b.id}))||[];
 const previewRows:Tree[]=tree.flatMap(n=>n.type==='table'?(n.rows||[]).map(row=>({type:'table',rows:[row]})):[n]);
 const blockMap=new Map(doc?.blocks.map(b=>[b.id,b]));
 const renderNodes=(nodes:Tree[],lang:string):React.ReactNode=>nodes.map((n,i)=>{if(n.type==='group')return <React.Fragment key={i}>{renderNodes(n.blocks||[],lang)}</React.Fragment>;if(n.type==='table')return <table key={i} className="bilingual-inner-table"><tbody>{n.rows?.map((r,j)=><tr key={j}>{r.cells.map((c,k)=><td key={k} colSpan={c.span}>{renderNodes(c.blocks,lang)}</td>)}</tr>)}</tbody></table>;const b=blockMap.get(n.id||'');if(!b)return null;return <div key={b.id} className={`bilingual-fragment${selected===b.id?' selected':''}${b.issues?.length?' needs-review':''}`}><button className={b.heading?'heading':''} onClick={()=>pick(b)} aria-label={`Выбрать пункт: ${(doc?.sourceLanguage===lang?b.source:b.translation).slice(0,70)}`}>{doc?.sourceLanguage===lang?b.source:b.translation||'Перевод готовится…'}</button>{!!b.issues?.length&&<p>{b.issues.join(' · ')}</p>}</div>;});
 if(renderedOwner!==owner||!owner)return null;
 return <section className={`bilingual-page${preview?' bilingual-preview':''}`} aria-label="Перевод документов">
  <header className="bilingual-header"><Link to="/c/new" aria-label="Вернуться в чат"><ArrowLeft size={18}/></Link><h1>Перевод документов</h1><button disabled={busy} onClick={()=>{accept(null);setPreview(false);setSelected('');setEdit(null);pending.current=null;setMessage('');setError('');}}><Plus size={17}/><span>Новый перевод</span></button></header>
  {error&&<div role="alert" className="bilingual-alert">{error}<button aria-label="Закрыть уведомление" onClick={()=>setError('')}><X size={16}/></button></div>}
  <div className="bilingual-layout"><aside className="bilingual-history"><h2>Мои переводы</h2>{!items.length&&<p>Здесь сохранятся ваши документы.</p>}{items.map(item=><div className={item.id===doc?.id?'selected':''} key={item.id}><button disabled={busy} onClick={()=>run(async()=>{accept(await(await api(`/${item.id}`)).json());setSelected('');setEdit(null);setMessage('');})}><strong>{item.title}</strong><small>{item.status==='processing'?'Обрабатывается…':`Версия ${item.revision}`}</small></button><button disabled={busy||item.status==='processing'} aria-label={`Удалить «${item.title}»`} onClick={()=>remove(item)}><Trash2 size={15}/></button></div>)}</aside>
  <main className="bilingual-main">
   {!!doc?.filename&&<div className="bilingual-document-bar"><span title={doc.filename}>{doc.title}</span><small>Версия {doc.revision}</small><button disabled={!complete||locked} onClick={download}><Download size={17}/>Word</button><button aria-label={preview?'Закрыть предпросмотр':'Открыть предпросмотр'} title={preview?'Закрыть предпросмотр':'Открыть предпросмотр'} onClick={()=>setPreview(!preview)}>{preview?<Minimize2 size={18}/>:<Maximize2 size={18}/>}</button></div>}
   {preview&&doc&&<div className="bilingual-paper" aria-label="Билингвальный предпросмотр"><div className="bilingual-columns"><strong>Русский</strong><strong>English</strong></div>{previewRows.map((n,i)=><div key={i} className="bilingual-pair"><div>{renderNodes([n],'ru')}</div><div>{renderNodes([n],'en')}</div></div>)}</div>}
   <BilingualChatContainer preview={preview} collapsed={collapsed} onToggle={()=>setCollapsed(!collapsed)}>
   <div className={preview?'bilingual-dock-body':'bilingual-conversation'}>
    {!collapsed||!preview?<div className="bilingual-messages" ref={scroll} aria-label="Диалог с переводчиком">
     {!doc?.filename&&<div className="bilingual-empty"><h2>Документ на двух языках</h2><p>Загрузите Word или PDF — агент подготовит русский и английский текст в двух колонках, сохранив пункты, таблицы и реквизиты.</p><button disabled={locked} onClick={()=>fileRef.current?.click()}><Paperclip size={18}/>Загрузить документ</button><small>DOCX или PDF · до 20 МБ · PDF до 80 страниц</small></div>}
     {doc?.chat.map((m,i)=><div className={`bilingual-message ${m.role}`} key={i}>{m.text}</div>)}
     {!!doc?.warnings.length&&<details className="bilingual-notes"><summary>Особенности исходного документа ({doc.warnings.length})</summary>{doc.warnings.map(w=><p key={w}>{w}</p>)}</details>}
     {doc?.error&&<div role="alert" className="bilingual-alert">{doc.error}</div>}
    </div>:null}
    {(locked||doc?.status==='processing')&&<div className="bilingual-progress" role="status"><LoaderCircle className="bilingual-spinner" size={17}/><span>{doc?.status==='processing'?doc.progress||'Агент работает…':'Загружаю документ…'}</span></div>}
    {chosen&&<div className="bilingual-selection"><span>Выбран пункт: {chosen.source.slice(0,100)}{chosen.source.length>100?'…':''}</span><button aria-label="Снять выбор пункта" onClick={()=>{setSelected('');setEdit(null);}}><X size={16}/></button>{edit===null?<button disabled={locked||!chosen.translation} onClick={()=>setEdit({source:chosen.source,translation:chosen.translation,revision:doc!.revision})}>Править вручную</button>:<>
     <div className="bilingual-manual-fields">{(['ru','en'] as const).map(lang=>{const field=doc?.sourceLanguage===lang?'source':'translation';return <label key={lang}>{lang==='ru'?'Русский текст':'English text'}<textarea aria-label={lang==='ru'?'Русский текст':'English text'} lang={lang} value={edit[field]} disabled={locked} onChange={e=>setEdit({...edit,[field]:e.target.value})}/></label>;})}</div>
     <small>Обе колонки сохранятся как новая версия документа.</small><button disabled={locked||!edit.source.trim()||!edit.translation.trim()||(edit.source===chosen.source&&edit.translation===chosen.translation)} onClick={saveManual}>Сохранить новую версию</button><button disabled={locked} onClick={()=>setEdit(null)}>Отмена</button></>}</div>}
    <form className="bilingual-composer" onSubmit={e=>{e.preventDefault();void submit();}}><textarea aria-label="Сообщение переводчику" maxLength={6000} rows={2} placeholder={doc?.filename?'Уточните перевод или попросите внести правки':'Сначала загрузите Word или PDF'} value={message} disabled={locked} onChange={e=>setMessage(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();void submit();}}}/><div><button type="button" aria-label="Прикрепить документ DOCX или PDF" disabled={locked||!!doc?.filename} onClick={()=>fileRef.current?.click()}><Paperclip size={20}/></button><span>RU / EN</span><button type="submit" aria-label="Отправить сообщение" disabled={locked||!message.trim()||!doc?.filename}><ArrowUp size={20}/></button></div></form>
   </div></BilingualChatContainer>
  </main></div><input hidden type="file" accept=".docx,.pdf,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document" ref={fileRef} onChange={e=>{const file=e.currentTarget.files?.[0];e.currentTarget.value='';void upload(file);}}/>
 </section>;
}
