const express=require('express'),multer=require('multer'),fs=require('fs/promises'),path=require('path'),os=require('os'),crypto=require('crypto');
const {requireJwtAuth,checkBan}=require('~/server/middleware');
const {createAiFeatureLimiter}=require('~/server/middleware/limiters/aiFeatureLimiters');
const store=require('../../services/Bilingual/store'),agent=require('../../services/Bilingual/agent');
const router=express.Router();router.use(requireJwtAuth,checkBan);
const limiter=createAiFeatureLimiter('bilingual'),upload=multer({dest:path.join(os.tmpdir(),'corp-bilingual'),limits:{fileSize:20*1024*1024,files:1,fields:2}});
const user=req=>{const id=String(req.user?._id||'');if(!/^[a-f0-9]{24}$/i.test(id)){const e=new Error('Требуется вход в аккаунт');e.status=401;throw e;}return id;},safe=fn=>(req,res,next)=>Promise.resolve(fn(req,res)).catch(next);
const view=d=>({...d,...(d.pdf?{pdf:{pageCount:d.pdf.pageCount,pages:d.pdf.pages.map(({number,status})=>({number,status}))}}:{}),blocks:d.blocks.map(({history,...b})=>({...b,historyCount:history?.length||0}))});
let jobs=0;
router.get('/',safe(async(req,res)=>res.json(await store.list(user(req)))));
router.post('/',safe(async(req,res)=>{const d={id:crypto.randomUUID(),title:'Новый перевод',revision:1,status:'draft',blocks:[],tree:[],warnings:[],chat:[],requests:[],instructions:''};await store.save(user(req),d);res.status(201).json(view(d));}));
router.get('/:id',safe(async(req,res)=>{let d=await store.read(user(req),req.params.id);if(d.status==='processing'&&!store.isBusy(user(req),d.id))d=await store.lock(user(req),d.id,async()=>{const fresh=await store.read(user(req),d.id);fresh.status='failed';fresh.error='Обработка прервалась. Отправьте «Продолжить», чтобы сохранить готовые пункты и завершить перевод.';return store.save(user(req),fresh);});res.json(view(d));}));
router.delete('/:id',safe(async(req,res)=>{await store.lock(user(req),req.params.id,async()=>{const d=await store.read(user(req),req.params.id);d.deletedAt=new Date().toISOString();await store.save(user(req),d);});res.status(204).end();}));
router.post('/:id/file',limiter,upload.single('file'),safe(async(req,res)=>{try{if(!req.file)return res.status(400).json({error:'Выберите файл DOCX или PDF'});const d=await store.lock(user(req),req.params.id,async()=>{const d=await store.read(user(req),req.params.id);if(d.filename||d.blocks.length)throw new Error('Создайте новый перевод для другого документа');let name=req.file.originalname;const decoded=Buffer.from(name,'latin1').toString('utf8');if(!decoded.includes('\ufffd'))name=decoded;const ext=path.extname(name).toLowerCase();if(!['.docx','.pdf'].includes(ext))throw new Error('Поддерживаются DOCX и PDF');const directory=store.dir(user(req),d.id);if(ext==='.pdf'){d.pdf=await require('../../services/Bilingual/parse-worker').parseFile(req.file.path,{type:'pdf',directory:path.join(directory,'pdf')});d.warnings.push('Текст PDF распознается моделью. Проверьте мелкий шрифт и нечеткие места в оригинале; изображения, подписи и печати не переносятся в Word как картинки.');d.chat.push({role:'assistant',text:`PDF загружен: ${d.pdf.pageCount} страниц. Прочитаю текст и сканы, восстановлю таблицы и подготовлю перевод. Прогресс появится ниже.`});}else{Object.assign(d,await require('../../services/Bilingual/parse-worker').parseFile(req.file.path));d.chat.push({role:'assistant',text:`Документ прочитан: ${d.blocks.length} фрагментов. Направление ${d.sourceLanguage==='ru'?'русский → английский':'английский → русский'}. Исходный текст сохраню без изменений.`});}Object.assign(d,{filename:name.slice(0,240),title:name.replace(/\.(docx|pdf)$/i,'').slice(0,160),status:'draft'});await fs.copyFile(req.file.path,path.join(directory,'source'+ext));return store.save(user(req),d);});res.json(view(d));}finally{if(req.file)await fs.unlink(req.file.path).catch(()=>{});}}));
router.post('/:id/chat',limiter,safe(async(req,res)=>{
 const u=user(req),id=req.params.id,message=String(req.body.message||'').trim(),requestId=String(req.body.requestId||''),selectedId=String(req.body.selectedId||'');
 if(!message||message.length>6000||! /^[a-zA-Z0-9_-]{1,100}$/.test(requestId))return res.status(400).json({error:'Введите сообщение до 6000 символов'});
 const digest=crypto.createHash('sha256').update(message+'|'+selectedId).digest('hex');
 if(store.isBusy(u,id)){const d=await store.read(u,id),old=d.requests.find(r=>r.id===requestId);return old?.digest===digest?res.status(202).json(view(d)):res.status(409).json({error:'Документ уже обрабатывается. Дождитесь завершения.'});}
 store.lock(u,id,async()=>{const d=await store.read(u,id),old=d.requests.find(r=>r.id===requestId);if(old){if(old.digest!==digest)return res.status(409).json({error:'Идентификатор запроса уже использован'});return res.json(view(d));}if(!d.blocks.length&&!d.pdf)return res.status(400).json({error:'Сначала загрузите документ DOCX или PDF'});if(jobs>=2)return res.status(429).json({error:'Два документа уже обрабатываются. Повторите позже.'});jobs++;try{d.requests.push({id:requestId,digest});d.chat.push({role:'user',text:message});if(d.pdf?.pages.some(p=>p.status!=='done')||d.blocks.some(b=>!b.translation))d.instructions=(d.instructions+'\n'+message).slice(-10000);d.status='processing';d.error=null;d.progress='Агент готовит перевод';await store.save(u,d);res.status(202).json(view(d));try{const save=()=>store.save(u,d);if(d.pdf)await require('../../services/Bilingual/pdf').extract(d,u,path.join(store.dir(u,id),'pdf'),save);if(!d.blocks.length)throw new Error('В документе нет распознанного текста для перевода');if(d.blocks.some(b=>!b.translation)){await agent.translate(d,u,save);}else await agent.revise(d,u,message,selectedId,save);d.status='ready';}catch(e){d.status='failed';d.error=/429|RESOURCE_EXHAUSTED/.test(e.message)?'Модель временно перегружена. Готовые пункты сохранены. Позже отправьте «Продолжить».':e.message;console.error('[bilingual-job]',e.message);}await store.save(u,d);}finally{jobs--;}}).catch(e=>{console.error('[bilingual-job]',e.message);if(!res.headersSent)res.status(e.code==='ENOENT'?404:e.status||500).json({error:e.code==='ENOENT'?'Документ не найден':'Не удалось запустить обработку'});});
}));
router.patch('/:id/block/:block',safe(async(req,res)=>{const d=await store.lock(user(req),req.params.id,async()=>{const d=await store.read(user(req),req.params.id);if(req.body.revision!==d.revision){const e=new Error('Документ изменился. Обновите его перед правкой.');e.status=409;throw e;}const b=d.blocks.find(b=>b.id===req.params.block);if(!b)throw new Error('Пункт не найден');const edit={id:b.id};for(const field of ['source','translation','text'])if(Object.hasOwn(req.body,field))edit[field]=req.body[field];const changed=agent.apply(d,[edit],undefined,{allowSource:true});if(changed){d.chat.push({role:'assistant',text:`Ручные правки сохранены. Версия ${d.revision}. Предпросмотр и Word обновлены.`});return store.save(user(req),d);}return d;});res.json(view(d));}));
router.get('/:id/export',safe(async(req,res)=>{const d=await store.read(user(req),req.params.id);if(store.isBusy(user(req),d.id))return res.status(409).json({error:'Дождитесь завершения правок'});const data=await require('../../services/Bilingual/export').exportDocument(d);res.set({'Content-Type':'application/vnd.openxmlformats-officedocument.wordprocessingml.document','Content-Disposition':`attachment; filename="Bilingual_v${d.revision}.docx"`});res.send(data);}));
router.use((e,req,res,next)=>{if(res.headersSent)return next(e);res.status(e.code==='ENOENT'?404:e.status||400).json({error:e.code==='ENOENT'?'Документ не найден':e.code==='LIMIT_FILE_SIZE'?'Размер файла не должен превышать 20 МБ':e.message||'Не удалось выполнить действие'});});
module.exports=router;
