const fs = require('fs').promises;
const path = require('path');
const { logger } = require('@librechat/data-schemas');
const { cleanFileName } = require('~/server/utils/files');

/**
 * Download an artifact generated by the internal supplier-analysis MCP tool.
 *
 * This route is mounted before JWT middleware because a normal Markdown link
 * opened by the browser cannot add LibreChat's Authorization header. The UUID
 * is a random bearer capability and the metadata enforces a short expiry.
 */
async function downloadSupplierArtifact(req, res) {
  const { token } = req.params;
  if (!/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(token)) {
    return res.status(400).send('Bad request');
  }

  const artifactDir = process.env.SUPPLIER_ARTIFACTS_DIR || '/app/uploads/supplier-artifacts';
  const metadataPath = path.join(artifactDir, `${token}.json`);
  try {
    const metadata = JSON.parse(await fs.readFile(metadataPath, 'utf8'));
    const storageName = path.basename(metadata.storageName || '');
    if (!storageName.startsWith(`${token}.`) || Date.parse(metadata.expiresAt) <= Date.now()) {
      return res.status(410).send('Artifact expired');
    }

    const artifactPath = path.join(artifactDir, storageName);
    await fs.access(artifactPath);
    res.setHeader('Cache-Control', 'private, no-store');
    res.setHeader('X-Content-Type-Options', 'nosniff');
    res.setHeader('Content-Type', metadata.mimeType || 'application/octet-stream');
    return res.download(artifactPath, cleanFileName(metadata.filename || storageName));
  } catch (error) {
    if (error?.code === 'ENOENT') return res.status(404).send('Artifact not found');
    logger.error('[supplier-artifacts] Download failed:', error);
    return res.status(500).send('Artifact download failed');
  }
}

module.exports = { downloadSupplierArtifact };
