const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const root=path.resolve(__dirname,'../..');
test('setup generates unique instance secrets without changing an existing configuration',()=>{
 const temp=fs.mkdtempSync(path.join(os.tmpdir(),'ai-corp-setup-'));try{fs.copyFileSync(path.join(root,'.env.example'),path.join(temp,'.env.example'));const {setup}=require('../setup.cjs');assert.equal(setup(temp),true);const first=fs.readFileSync(path.join(temp,'.env'),'utf8');assert.ok(!first.includes('CHANGE_ME'));const values=Object.fromEntries(first.split('\n').filter(l=>/^[A-Z_]+=/.test(l)).map(l=>{const i=l.indexOf('=');return [l.slice(0,i),l.slice(i+1)]}));assert.equal(values.CREDS_KEY.length,64);assert.equal(values.CREDS_IV.length,32);assert.notEqual(values.JWT_SECRET,values.JWT_REFRESH_SECRET);assert.ok(values.MONGO_URI.includes(values.MONGO_PASSWORD));assert.ok(values.TOKEN_USAGE_DB_URL.includes(values.POSTGRES_PASSWORD));assert.equal(values.DEEPSEEK_API_KEY,'');assert.equal(values.GOOGLE_KEY,'');assert.equal(setup(temp),false);assert.equal(fs.readFileSync(path.join(temp,'.env'),'utf8'),first);}finally{assert.ok(temp.startsWith(path.join(os.tmpdir(),'ai-corp-setup-')));fs.rmSync(temp,{recursive:true,force:true});}
});
test('assistant seed retains tool and development capabilities but no original ownership or documents',()=>{const {agents}=require('../../config/seed/agents.json');assert.equal(agents.length,10);assert.equal(new Set(agents.map(a=>a.id)).size,10);assert.equal(agents.filter(a=>a.ipr_enabled).length,8);assert.ok(agents.every(a=>a.instructions&&a.name&&!a.author&&!a.avatar&&!a.tool_resources&&!a.versions));assert.ok(agents.some(a=>a.tools.includes('check_supplier_reputation_mcp_supplier-tools')));assert.ok(agents.some(a=>a.ipr_target==='NEWCOMER_MP'));});
test('market analysis is available to authenticated accounts without employee whitelists',()=>{const policy=require('../../api/server/services/accountFeatureAccess');assert.equal(policy.canUseMarketAnalysis({_id:'new-user',email:'new@example.com'}),true);assert.equal(policy.canUseMarketAnalysis(null),false);assert.deepEqual(policy.hiddenAgentIds({email:'new@example.com'}),[]);});
test('public scanner flags credential material without exposing its value',()=>{const {problems}=require('../check-public.cjs');assert.equal(problems('ordinary source','safe.js').length,0);assert.match(problems('-----BEGIN PRIVATE KEY-----','bad.json')[0],/private key/);assert.ok(!problems('sk-'+('x'.repeat(32)),'bad.js')[0].includes('xxxx'));});

test('market export keeps two user sheets, formulas, ranking and consistent totals',async()=>{
 const {aggregate}=require('../../api/server/services/MarketAnalysis/core');const {exportWorkbook}=require('../../api/server/services/MarketAnalysis/export');const ExcelJS=require('../../api/server/services/MarketAnalysis/node_modules/exceljs');
 const records=[];for(const year of ['2024','2025'])for(const [brand,units,price]of [['Demo A',100,10],['Demo B',50,20],['Demo C',25,8]])records.push({brand,sku:brand,inn:'Demo ingredient',form:'Demo form',dosage:'10 mg',pack:'30',period:year,source:'AlphaRM',scope:'Synthetic test',units,sales:units*price,price,location:'Synthetic!1'});
 const params={primarySource:'AlphaRM',priceMethod:'weighted',rankBy:'units',topN:2};const a={title:'Synthetic market',params,result:aggregate(records,params),tables:[],facts:[],files:[],comments:[],notes:[],productInfo:[]};assert.deepEqual(a.result.brands.map(b=>b.brand),['Demo A','Demo B','Другие']);assert.equal(a.result.totals['2025'].sales,2200);
 const w=new ExcelJS.Workbook();await w.xlsx.load(await exportWorkbook(a));assert.equal(w.worksheets.length,2);assert.equal(w.worksheets[1].name,'Конкуренты');assert.deepEqual(w.worksheets[1].getRow(1).values.slice(1),['Торговое наименование','МНН, форма и фасовка','Показания']);let formulas=0;w.worksheets[0].eachRow(row=>row.eachCell(cell=>{if(cell.formula)formulas++}));assert.ok(formulas>0);a.result.totals['2025'].sales++;await assert.rejects(()=>exportWorkbook(a),/контрольные суммы/);
});
