const core=require('./core');
const months=['янв','фев','мар','апр','май','июн','июл','авг','сен','окт','ноя','дек'];
function parseMonth(value){const s=core.norm(value);const m=s.match(/^([а-яё]+)\.?\s+((?:19|20)\d{2})$/);if(m){const i=months.findIndex(x=>m[1].startsWith(x)||(x==='май'&&m[1].startsWith('мая')));if(i>=0)return `${m[2]}-${String(i+1).padStart(2,'0')}`;}return core.period(value);}
function validate(table,m){const width=Math.max(0,...table.rows.slice(0,100).map(r=>r.length));const col=c=>{if(!Number.isInteger(c)||c<0||c>=width)throw new Error('Колонка преобразования вне таблицы');};
 if(m.filters!=null){if(!Array.isArray(m.filters)||m.filters.length>10)throw new Error('Не более 10 фильтров');for(const f of m.filters){col(f.column);if(!['in','notIn'].includes(f.op)||!Array.isArray(f.values)||!f.values.length||f.values.length>200||f.values.some(v=>!['string','number'].includes(typeof v)))throw new Error('Фильтр: column, op=in|notIn, values');}}
 if(m.fillDown!=null){if(!Array.isArray(m.fillDown)||m.fillDown.length>12)throw new Error('Некорректное заполнение иерархии');for(const c of m.fillDown){col(c);if([m.columns?.units,m.columns?.sales,m.columns?.price,m.columns?.period,...(m.wide||[]).map(w=>w.column)].includes(c))throw new Error('Нельзя заполнять пропуски чисел или периода предыдущим значением');}}
 if(m.normalization!=null){const n=m.normalization;if(!n||!['month','year'].includes(n.period)||Object.keys(n).some(k=>!['period','sumRegions','compareYtd'].includes(k))||['sumRegions','compareYtd'].some(k=>n[k]!=null&&typeof n[k]!=='boolean'))throw new Error('Нормализация: period=month|year, sumRegions, compareYtd');if(n.sumRegions&&m.columns?.region==null)throw new Error('Для суммирования регионов нужна колонка region');if(m.columns?.period==null&&!m.wide?.length)throw new Error('Для нормализации нужен период исходных строк');}
}
function inspect(table,q){const columns=q.columns||[q.column];if(!Array.isArray(columns)||!columns.length||columns.length>12||columns.some(c=>!Number.isInteger(c)||c<0||c>=500))throw new Error('Укажите до 12 индексов колонок');const start=table.mapping?.headerRow||1;const rows=table.rows;const limit=Math.min(80,Math.max(1,q.limit||20));
 if(q.kind==='columns'){return {tableId:table.id,columns:columns.map(c=>{const counts=new Map();let missing=0,numeric=0,min=null,max=null;for(let i=start;i<rows.length;i++){const v=rows[i][c];if(v==null||v===''){missing++;continue;}const k=String(v);counts.set(k,(counts.get(k)||0)+1);const n=core.number(v);if(n!=null){numeric++;min=min==null?n:Math.min(min,n);max=max==null?n:Math.max(max,n);}}return {column:c,header:rows[start-1]?.[c],missing,numeric,min,max,distinct:counts.size,values:[...counts].slice(0,limit).map(([value,count])=>({value,count})),truncated:counts.size>limit};})};}
 if(q.kind==='find'){if(typeof q.query!=='string'||!q.query.trim()||q.query.length>200)throw new Error('Укажите текст для поиска');const found=[];let count=0;for(let i=start;i<rows.length;i++)if(columns.some(c=>core.norm(rows[i][c]).includes(core.norm(q.query)))){count++;if(found.length<limit)found.push({row:i+1,values:rows[i]});}return {tableId:table.id,count,rows:found};}
 if(q.kind==='duplicates'){const seen=new Map(),examples=[];let count=0;for(let i=start;i<rows.length;i++){const key=JSON.stringify(columns.map(c=>core.norm(rows[i][c])));if(seen.has(key)){count++;if(examples.length<limit)examples.push({first:seen.get(key),row:i+1,values:columns.map(c=>rows[i][c])});}else seen.set(key,i+1);}return {tableId:table.id,duplicateCount:count,examples};}
 throw new Error('Неизвестный инструмент исследования');
}
function prepare(table,m,source,scope){if(m.columns.tradeName==null){const c=(table.rows[m.headerRow-1]||[]).findIndex(v=>/^(лс\.)?торговое наименование$/i.test(String(v).trim()));if(c>=0)m={...m,columns:{...m.columns,tradeName:c}};}validate(table,m);const excluded=new Set(m.excludeRows||[]),last={};let filtered=0;const filters=(m.filters||[]).map(f=>({...f,set:new Set(f.values.map(core.norm))}));const rows=table.rows.map((original,i)=>{if(i<m.headerRow||i>=(m.endRow||table.rows.length)||excluded.has(i+1))return original;const row=[...original];for(const c of m.fillDown||[]){if(row[c]!=null&&row[c]!=='')last[c]=row[c];else if(row.some(v=>v!=null&&v!==''))row[c]=last[c]??row[c];}if(filters.some(f=>f.op==='in'?!f.set.has(core.norm(row[f.column])):f.set.has(core.norm(row[f.column])))){excluded.add(i+1);filtered++;return row;}if(m.normalization&&m.columns.period!=null){try{row[m.columns.period]=parseMonth(row[m.columns.period]);}catch{ /* mappedRows supplies precise row diagnostic */ }}return row;});
 const out=core.mappedRows({...table,rows},{...m,excludeRows:[...excluded]},source,scope);if(out.issues.length||!m.normalization)return {...out,audit:{tableId:table.id,inputRows:table.rows.length-m.headerRow,filteredRows:filtered,records:out.records.length}};
 const n=m.normalization,seen=new Map(),coverage=new Map();const keys=['brand','tradeName','sku','manufacturer','inn','form','dosage','pack','registration'];
 for(const r of out.records){const grain=JSON.stringify([r.sku||keys.map(k=>r[k]),r.period,r.country,r.channel,r.region]);if(seen.has(grain))throw new Error(`Повтор исходной позиции: ${r.brand}, ${r.period}, ${r.region||'без региона'}; ${seen.get(grain)} и ${r.location}. Проверьте зерно данных, не удаляйте строки автоматически.`);seen.set(grain,r.location);if(!/^\d{4}-\d{2}$/.test(r.period))throw new Error(`Для помесячной нормализации нужен месяц: ${r.location}, ${r.period}`);const year=r.period.slice(0,4);if(!coverage.has(year))coverage.set(year,new Set());coverage.get(year).add(+r.period.slice(5));if(r.units==null||r.sales==null)throw new Error(`Пропуск рублей или упаковок: ${r.location}`);}
 if(new Set(out.records.map(r=>r.country)).size>1||new Set(out.records.map(r=>r.channel)).size>1)throw new Error('Разные страны или каналы: примените фильтр до суммирования');
 if(new Set(out.records.map(r=>r.region)).size>1&&out.records.some(r=>/^(итого|всего|россия|рф|total|all regions)$/i.test(r.region.trim())))throw new Error('Региональные строки смешаны с общим итогом; отфильтруйте один уровень');
 if(!n.sumRegions&&new Set(out.records.map(r=>r.region)).size>1)throw new Error('Несколько регионов: явно задайте sumRegions:true или фильтр региона');
 const labels=new Map();for(const [y,ms]of coverage){const sorted=[...ms].sort((a,b)=>a-b);if(sorted.some((v,i)=>i&&v!==sorted[i-1]+1))throw new Error(`Пропущены месяцы внутри ${y}; годовой итог недостоверен`);labels.set(y,sorted.length===12?y:`${y}-${String(sorted[0]).padStart(2,'0')}-${String(sorted.at(-1)).padStart(2,'0')}`);}
 const latest=[...coverage.keys()].sort().at(-1),latestMonths=coverage.get(latest);const previous=String(+latest-1);const compare=n.period==='year'&&n.compareYtd&&latestMonths?.size<12&&coverage.has(previous)&&labels.get(previous)!==labels.get(latest).replace(latest,previous)&&[...latestMonths].every(m=>coverage.get(previous).has(m));const comparisonLabel=compare?labels.get(latest).replace(latest,previous):null;
 const groups=new Map();const totals={};const add=(r,p)=>{const key=JSON.stringify([...keys.map(k=>core.norm(r[k])),p]);let g=groups.get(key);if(!g){g={...r,id:core.id(),period:p,units:0,sales:0,price:null,rawPriceSum:0,rawPriceCount:0,rawRowCount:0,lineage:[],location:table.name+' · агрегировано'};groups.set(key,g);}g.units+=r.units;g.sales+=r.sales;g.rawRowCount++;if(r.price!=null){g.rawPriceSum+=r.price;g.rawPriceCount++;}g.lineage.push({tableId:table.id,row:Number(r.location.match(/строка (\d+)$/)?.[1]),period:r.period,region:r.region});totals[p]||={units:0,sales:0};totals[p].units+=r.units;totals[p].sales+=r.sales;};
 for(const r of out.records){const y=r.period.slice(0,4);add(r,n.period==='month'?r.period:labels.get(y));if(compare&&y===previous&&latestMonths.has(+r.period.slice(5)))add(r,comparisonLabel);}
 const records=[...groups.values()].map(g=>({...g,region:n.sumRegions?'Все выбранные регионы':g.region,price:g.units?g.sales/g.units:null,location:`${table.name} · ${g.lineage.length} исходных строк`}));return {records,issues:[],audit:{tableId:table.id,inputRows:table.rows.length-m.headerRow,filteredRows:filtered,records:out.records.length,normalizedRecords:records.length,normalization:n,coverage:[...coverage].map(([year,ms])=>({year,months:[...ms].sort((a,b)=>a-b),label:labels.get(year)})),totals,comparisonPeriod:comparisonLabel,warning:compare?'Сопоставимый неполный период повторяет часть полного года; периоды нельзя суммировать между собой.':null}};
}
module.exports={parseMonth,validate,inspect,prepare};
